server:
  port: ${PORT:8080}
spring:
  application:
    name: ${APP_NAME:back-ms-franquicias-java}
  datasource:
    url: ${DB_URL:jdbc:postgresql://db-nequi.c5aq8qusmthf.us-east-1.rds.amazonaws.com:5432/db-nequi}
    username: ${DB_USER:nequi_db}
    password: ${DB_PASSWORD:Nequi2025..}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false